service: upload-file-to-s3-for-chatbots
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  timeout: 15
  environment:
    AWS_ACCESS_KEY_IDD: 'AKIA6O2CZXAF6PZPILFK'
    AWS_SECRET_ACCESS_KEYY: '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'
    AWS_BUCKET_NAME: 'base64-to-file'
    ENCODE_BASE: 'base64'
    DEBUG: '*'
functions:
  app:
    handler: lambda/custom/index.handler
    events:
      - http: POST /